name: Windows

on:
  push:
  pull_request:

jobs:
  build_frozen:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        cmake_args:
          - ""
        cxxstandard:
          - 14
          - 17
          - 2a
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Configure
      env:
          CXXFLAGS: /std:c++${{matrix.cxxstandard}}
      run: cmake -DCMAKE_BUILD_TYPE=DEBUG "-Dfrozen.coverage=ON" -DCMAKE_VERBOSE_MAKEFILE=ON -B build -S .

    - name: Build
      run: cmake --build build
